### ISSUE TITLE
Mollie::Method::all returning voucher on fresh created account

### ISSUE THREAD

**Issue by nflorentin** [mollie/mollie-api-ruby#154] opened 2021-08-24 13:12 UTC
Hi,

On a recently created Mollie account, a call to the api with:
```ruby
::Mollie::Method.all(api_key: "XXXXXXXXXXXXXXXX", include: 'issuers', resource: 'orders')
```
returns the voucher payment method which is not activated in Mollie dashboard, as seen on the following screenshot:
![Capture d’écran 2021-08-24 à 15 08 47](https://user-images.githubusercontent.com/5750349/130621994-484fa398-3778-4a82-8bb9-8d62ac1d27b9.png)

If I remove `resource: 'orders'` from the parameters, the voucher payment method **disappears** from the result.

The problem is I can't remove this parameter because I'm using the gem spree-mollie-gateway which uses those parameters [here](https://github.com/mollie/spree-mollie-gateway/blob/4219cfe244feecd0982f877470f8462fb6ddcf7b/app/models/spree/gateway/mollie_gateway.rb#L155).

It makes the payment method "voucher" appearing in my Spree app. 

By the way, the gem spree-mollie-gateway uses the version 4.2.0 of mollie-api-ruby, which is seems a bit outdated...

Thanks in advance for your help.

**Comment by justincase** [comment] 2021-08-25 16:55
Hi @nflorentin,

Thanks for the detailed bug report. It appears to be a bug in the API response. The issue has been forwarded to the correct team at Mollie. I'll update this ticket when I have more information.

**Comment by justincase** [comment] 2022-12-01 23:27
Closing this issue since it's not a bug in the Ruby client itself. If the issue persists I suggest contacting Mollie support directly: https://www.mollie.com/nl/contact/merchants.

Thanks!

**Closed by justincase** 2022-12-01 23:27 UTC
